In [2]:
import importlib
import numpy as np

In [76]:
import debiasedModel2 as db
import policies
importlib.reload(db)
importlib.reload(policies)

n_rows = 5
n_features = 3
pred_dim = n_features 
max_depth = 10

xs = np.random.normal(size=(n_rows, n_features))
slopes = np.random.uniform(size = n_features)
errs = np.random.normal(scale=0.01, size = (n_rows, n_features))
ys = np.multiply(xs, slopes) + errs

# just predicts label mean
def h1(xs):
    # calculate label mean and duplicate it for each of xs
    return np.tile(np.average(ys, axis=0), (len(xs),1))

def h2(xs):
    preds = np.zeros((len(xs), n_features), dtype='float64')
    preds[:,0] = ys[:,0]
    return preds

h1_policy = policies.Simplex(pred_dim, h1)
h2_policy = policies.Simplex(pred_dim, h2)

init_model = h1
max_depth = 10

model = db.Debiased_model(max_depth, h1_policy, pred_dim, h2, xs)
model.debias(ys, h2_policy)

0
3
0
3
0
3
0
3
0
3
1
3
2
3
Halting early at round  6


In [31]:
model.bias_array

[array([ 0.        , -0.3312291 , -0.00090232]),
 array([0.        , 0.21355704, 0.02601576]),
 array([ 0.        ,  0.55861456, -0.22349648]),
 array([ 0.        , -0.08205657, -0.30154375]),
 array([ 0.        , -0.18620485,  0.07449883]),
 array([0., 0., 0.]),
 array([0., 0., 0.]),
 array([0., 0., 0.]),
 array([0., 0., 0.]),
 array([0., 0., 0.])]

In [73]:
importlib.reload(db)

xs = np.array([[1],[2],[3]]) 
ys = np.array([[1,10], [1,0], [1,0]])

def h(xs):
    preds = []
    for x in xs:
        if x==1:
            preds.append([5.,10.])
        if x==2:
            preds.append([1,0])
        if x==3:
            preds.append([9,0])
    return np.array(preds)

max_depth = 8
pred_dim = 2
simp = policies.Simplex(pred_dim, h)
model = db.Debiased_model(max_depth, simp, pred_dim, h, xs)
model.debias(ys, simp);

In [74]:
model.predictions_by_round

[array([[ 5., 10.],
        [-3.,  0.],
        [ 1.,  0.]]),
 array([[ 5., 10.],
        [-3.,  0.],
        [ 5.,  0.]]),
 array([[ 5., 10.],
        [-3.,  0.],
        [ 5.,  0.]]),
 array([[ 5., 10.],
        [-3.,  0.],
        [ 1.,  0.]]),
 array([[ 5., 10.],
        [-3.,  0.],
        [ 1.,  0.]]),
 array([[ 5., 10.],
        [-3.,  0.],
        [ 1.,  0.]]),
 array([[ 5., 10.],
        [-3.,  0.],
        [ 1.,  0.]]),
 array([[ 5., 10.],
        [-3.,  0.],
        [ 1.,  0.]]),
 array([[ 5., 10.],
        [-3.,  0.],
        [ 1.,  0.]])]